version: '3.8'

services:
  sindicatos_api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sindicatos_api-${ENV}
    container_name: sindicatos_api-${ENV}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - SV_ADDR=0.0.0.0:${PORT}
      - CONN_POSTGRES=${CONN_POSTGRES}
    # volumes:
      # - .:/app
    command: /sindicatos-api
    networks:
      - sindicatos-network
networks:
  sindicatos-network:
    driver: bridge
